### ISSUE TITLE
Nuxt-Palette Roadmap

### ISSUE THREAD

**Issue by TutorFx** [TutorFx/nuxt-palette#12]
## Core Features

- [x] Multiple color scheme management (light, dark, etc.)
- [x] CSS variable generation in `root-styles`
- [x] Automatic Tailwind config generation
- [x] Color mode library pre-installation & setup
- [x] Simple API for color definition & access
- [ ] Basic documentation with usage examples

## UI Library Integration & Accessibility

- [ ] **UI Library Support:**
    - [x] Shadcn
    - [ ] PrimeVue
    - [ ] Nuxt UI
    - [ ] More soon...
- [ ] Foreground/background contrast validation (WCAG compliance)

## Nuxt Layers & Advanced Features

- [ ] Nuxt Layers support
